PSAT("internal", CPP_TOKEN_KEY_QUALIFIER),
PSAT("auto", CPP_TOKEN_KEY_QUALIFIER),
PSAT("fox_for", CPP_TOKEN_KEY_CONTROL_FLOW),

PSAT("u8", CPP_TOKEN_KEY_TYPE),
PSAT("u16", CPP_TOKEN_KEY_TYPE),
PSAT("u32", CPP_TOKEN_KEY_TYPE),
PSAT("u64", CPP_TOKEN_KEY_TYPE),

PSAT("s8", CPP_TOKEN_KEY_TYPE),
PSAT("s16", CPP_TOKEN_KEY_TYPE),
PSAT("s32", CPP_TOKEN_KEY_TYPE),
PSAT("s64", CPP_TOKEN_KEY_TYPE),

PSAT("b8", CPP_TOKEN_KEY_TYPE),
PSAT("b16", CPP_TOKEN_KEY_TYPE),
PSAT("b32", CPP_TOKEN_KEY_TYPE),
PSAT("b64", CPP_TOKEN_KEY_TYPE),

PSAT("f8", CPP_TOKEN_KEY_TYPE),
PSAT("f16", CPP_TOKEN_KEY_TYPE),
PSAT("f32", CPP_TOKEN_KEY_TYPE),
PSAT("f64", CPP_TOKEN_KEY_TYPE),
